const intervalBaseEnum = {
    UNISON: "UNISON",
    SECOND: "SECOND",
    THIRD: "THIRD",
    FOURTH: "FOURTH",
    FIFTH: "FIFTH",
    SIXTH: "SIXTH",
    SEVENTH: "SEVENTH",
    OCTAVE: "OCTAVE"
};

const intervalEnum = {
    DIMINISHED_UNISON: "DIMINISHED_UNISON",
    PERFECT_UNISON: "PERFECT_UNISON",
    AUGMENTED_UNISON: "AUGMENTED_UNISON",

    DIMINISHED_SECOND: "DIMINISHED_SECOND",
    MINOR_SECOND: "MINOR_SECOND",
    MAJOR_SECOND: "MAJOR_SECOND",
    AUGMENTED_SECOND: "AUGMENTED_SECOND",

    DIMINISHED_THIRD: "DIMINISHED_THIRD",
    MINOR_THIRD: "MINOR_THIRD",
    MAJOR_THIRD: "MAJOR_THIRD",
    AUGMENTED_THIRD: "AUGMENTED_THIRD",

    DIMINISHED_FOURTH: "DIMINISHED_FOURTH",
    PERFECT_FOURTH: "PERFECT_FOURTH",
    AUGMENTED_FOURTH: "AUGMENTED_FOURTH",

    DIMINISHED_FIFTH: "DIMINISHED_FIFTH",
    PERFECT_FIFTH: "PERFECT_FIFTH",
    AUGMENTED_FIFTH: "AUGMENTED_FIFTH",

    DIMINISHED_SIXTH: "DIMINISHED_SIXTH",
    MINOR_SIXTH: "MINOR_SIXTH",
    MAJOR_SIXTH: "MAJOR_SIXTH",
    AUGMENTED_SIXTH: "AUGMENTED_SIXTH",

    DIMINISHED_SEVENTH: "DIMINISHED_SEVENTH",
    MINOR_SEVENTH: "MINOR_SEVENTH",
    MAJOR_SEVENTH: "MAJOR_SEVENTH",
    AUGMENTED_SEVENTH: "AUGMENTED_SEVENTH",

    DIMINISHED_OCTAVE: "DIMINISHED_OCTAVE",
    PERFECT_OCTAVE: "PERFECT_OCTAVE",
    AUGMENTED_OCTAVE: "AUGMENTED_OCTAVE",
}

class Interval {
    constructor(note1, note2) {
        this.note1 = note1;
        this.note2 = note2;
    }

    calculateInterval() {
        console.log(this.note1.getRootNoteIndex());
        console.log(this.note2.getRootNoteIndex());
    }

    toString() {
        return this.note1.toString() + " - " + this.note2.toString();
    }
};